# Generated by Django 5.1.7 on 2025-04-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
